// Code generated by sqlc. DO NOT EDIT.

import { Database } from "better-sqlite3";

export const getUserQuery = `-- name: GetUser :one
SELECT id, username, updated_at, created_at
FROM users
WHERE
  -- id = sqlc.arg(id)
  id = ?
LIMIT 1`;

export interface GetUserArgs {
    id: number;
}

export interface GetUserRow {
    id: number;
    username: any;
    updatedAt: Date;
    createdAt: Date;
}

export async function getUser(database: Database, args: GetUserArgs): Promise<GetUserRow | null> {
    const stmt = database.prepare(getUserQuery);
    const result = await stmt.get(args.id);
    if (result == undefined) {
        return null;
    }
    return result as GetUserRow;
}

